name: Test Release Creation

on:
  push:
    branches:
      - release-test

permissions:
  contents: write  # Needed for GITHUB_TOKEN usage

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history

      - name: Fetch all branches
        run: |
          git fetch origin +refs/heads/*:refs/remotes/origin/*

      - name: Get Changelog Entry
        id: changelog
        run: |
          set -e
          changelog=$(sed -n '/^## Version /{n; :a;p;n;/^$/q;ba}' CHANGELOG.md | sed '/^$/d')
          changelog=$'\n'"${changelog}"$'\n'
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "content=$changelog" >> $GITHUB_OUTPUT

      - name: Get Contributors and Commits
        id: contributors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e  # Exit on any error
          trap 'echo "Error on line $LINENO"; exit 1' ERR

          REPO_URL="https://github.com/${{ github.repository }}"
          declare -A email_to_username
          declare -A email_to_name

          # Step 1: Build email-to-username map
          git log --format='%ae%x09%an' | sort -u > author_emails.txt
          if [[ ! -s author_emails.txt ]]; then
            echo "Error: author_emails.txt is empty"
            exit 1
          fi
          while IFS=$'\t' read -r email name; do
            email_to_name["$email"]="$name"
            if [[ "$email" =~ [0-9]+\+([^@]+)@users\.noreply\.github\.com ]]; then
              username="${BASH_REMATCH[1]}"
              email_to_username["$email"]="$username"
            else
              response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/search/users?q=$email+in:email")
              username=$(echo "$response" | jq -r '.items[0].login // ""')
              if [[ -n "$username" && "$username" != "null" ]]; then
                email_to_username["$email"]="$username"
              else
                email_to_username["$email"]=""
              fi
            fi
          done < author_emails.txt

          # Step 2: Process commits with quoted messages
          git log --format="%h%x09%ae%x09%s" > commits_raw.txt
          if [[ ! -s commits_raw.txt ]]; then
            echo "Error: commits_raw.txt is empty"
            exit 1
          fi
          > commits_info.txt  # Initialize file
          while IFS=$'\t' read -r hash email message; do
            escaped_message="${message//\#/\\#}"
            escaped_message="${escaped_message//%/\\%}"
            escaped_message="${escaped_message//\"/\\\"}"  # Escape double quotes
            username="${email_to_username[$email]}"
            name="${email_to_name[$email]}"
            if [[ -z "$username" ]]; then
              response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/commits/$hash")
              username=$(echo "$response" | jq -r '.author.login // .committer.login // ""')
              if [[ -n "$username" && "$username" != "null" ]]; then
                email_to_username["$email"]="$username"
              fi
            fi
            if [[ -n "$username" ]]; then
              echo "$hash|$email|$username|\"$escaped_message\"" >> commits_info.txt
            else
              echo "$hash|$email||\"$escaped_message\"" >> commits_info.txt
            fi
          done < commits_raw.txt

          # Step 3: Verify commits_info.txt
          if [[ ! -s commits_info.txt ]]; then
            echo "Error: commits_info.txt is empty after processing"
            exit 1
          fi
          echo "Commits info generated successfully."

          # Contributors: deduplicate by username and sort by commit count
          declare -A username_to_count
          declare -A username_to_name
          while IFS='|' read -r hash email username message; do
            # Strip leading and trailing quotes from message
            message="${message#\"}"
            message="${message%\"}"
            if [[ -n "$username" ]]; then
              username_to_count["$username"]=$(( ${username_to_count["$username"]:-0} + 1 ))
              username_to_name["$username"]="${email_to_name[$email]}"
            else
              username_to_count["$email"]=$(( ${username_to_count["$email"]:-0} + 1 ))
              username_to_name["$email"]="${email_to_name[$email]}"
            fi
          done < <(cat commits_info.txt)
          contributors=$(for key in "${!username_to_count[@]}"; do
            count="${username_to_count[$key]}"
            name="${username_to_name[$key]}"
            if [[ "$key" =~ ^[^@] ]]; then  # Username (not email)
              if [[ "$name" =~ " " ]]; then
                echo "$count|$name|[@$key](https://github.com/$key)"
              else
                echo "$count|[@$key](https://github.com/$key)|[@$key](https://github.com/$key)"
              fi
            else  # Email (no username)
              echo "$count|$name|"
            fi
          done | sort -nr | cut -d'|' -f2- | sed 's/^/* /')
          echo "Final contributors list:"
          echo "$contributors"

          # Commits: format with proper escaping
          commits=$(while IFS='|' read -r hash email username message; do
            message="${message#\"}"
            message="${message%\"}"
            if [[ -n "$username" ]]; then
              printf "* [%s](%s/commit/%s) %s ([@%s](https://github.com/%s))\n" "$hash" "$REPO_URL" "$hash" "$message" "$username" "$username"
            else
              name="${email_to_name[$email]}"
              printf "* [%s](%s/commit/%s) %s (%s)\n" "$hash" "$REPO_URL" "$hash" "$message" "$name"
            fi
          done < <(cat commits_info.txt) | sed 's/%/%25/g')

          # Set outputs
          {
            echo "list<<EOF_CONTRIBUTORS"
            echo "$contributors"
            echo "EOF_CONTRIBUTORS"
          } >> $GITHUB_OUTPUT
          {
            echo "commits<<EOF_COMMITS"
            echo "$commits"
            echo "EOF_COMMITS"
          } >> $GITHUB_OUTPUT

      - name: Display Release Content
        run: |
          echo "### Changes"
          echo "${{ steps.changelog.outputs.content }}" | sed 's/%0A/\n/g'
          echo "_For more details, see the full [changelog](${{ github.server_url }}/${{ github.repository }}/blob/master/CHANGELOG.md) in the repository_"
          echo ""
          echo "### Contributors"
          echo "${{ steps.contributors.outputs.list }}"
          echo ""
          echo "### Commits"
          echo "${{ steps.contributors.outputs.commits }}"
