name: Test Release Creation

on:
  push:
    branches:
      - release-test

permissions:
  contents: write  # Included for consistency, though not strictly needed for logging

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history

      - name: Fetch all branches
        run: |
          git fetch origin +refs/heads/*:refs/remotes/origin/*

      - name: Get Changelog Entry
        id: changelog
        run: |
          changelog=$(sed -n '/^## Version /{n; :a;p;n;/^$/q;ba}' CHANGELOG.md | sed '/^$/d')
          changelog=$'\n'"${changelog}"$'\n'
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "content=$changelog" >> $GITHUB_OUTPUT

      - name: Get Contributors and Commits
        id: contributors
        run: |
          REPO_URL="https://github.com/${{ github.repository }}"
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "none")
          # Normalize and get unique contributors by email to avoid duplicates
          contributors=$(git log --format='%an <%ae>' | sort -u | while read -r line; do
            full_name=$(echo "$line" | sed 's/ <.*>//')
            email=$(echo "$line" | sed 's/.*<\(.*\)>/\1/' | tr '[:upper:]' '[:lower:]')
            username=$(echo "$email" | cut -d'@' -f1)
            if echo "$full_name" | grep -q " "; then
              echo "* $full_name ([@$username](https://github.com/$username))"
            else
              echo "* [@$full_name](https://github.com/$full_name)"
            fi
          done | sort -u)
          # Escape % in commit messages and write to file
          git log --format='* [%h]('$REPO_URL'/commit/%H) %s ([%an](https://github.com/%an))' | sed 's/%/%25/g' > commits.txt
          commits=$(cat commits.txt)
          # Use GitHub Actions multi-line output syntax with a delimiter
          delimiter=$(openssl rand -hex 8)
          {
            echo "list<<$delimiter"
            echo "$contributors"
            echo "$delimiter"
          } >> $GITHUB_OUTPUT
          {
            echo "commits<<$delimiter"
            echo "$commits"
            echo "$delimiter"
          } >> $GITHUB_OUTPUT

      - name: Debug Outputs
        run: |
          echo "Raw changelog output:"
          echo "${{ steps.changelog.outputs.content }}" > changelog.txt
          cat changelog.txt
          echo ""
          echo "Raw contributors output:"
          echo "${{ steps.contributors.outputs.list }}" > contributors.txt
          cat contributors.txt
          echo ""
          echo "Raw commits output:"
          cat commits.txt

      - name: Display Release Content
        run: |
          echo "### Changes"
          echo "${{ steps.changelog.outputs.content }}" | sed 's/%0A/\n/g'
          echo "_For more details, see the full [changelog](${{ github.server_url }}/${{ github.repository }}/blob/master/CHANGELOG.md) in the repository_"
          echo ""
          echo "### Contributors"
          echo "${{ steps.contributors.outputs.list }}"
          echo ""
          echo "### Commits"
          cat commits.txt
