name: Test Release Creation

on:
  push:
    branches:
      - release-test

permissions:
  contents: write  # Included for consistency, though not strictly needed for logging

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history

      - name: Fetch all branches
        run: |
          git fetch origin +refs/heads/*:refs/remotes/origin/*

      - name: Get Changelog Entry
        id: changelog
        run: |
          changelog=$(sed -n '/^## Version /{n; :a;p;n;/^$/q;ba}' CHANGELOG.md | sed '/^$/d')
          changelog=$'\n'"${changelog}"$'\n'
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "content=$changelog" >> $GITHUB_OUTPUT

      - name: Get Contributors and Commits
        id: contributors
        run: |
          REPO_URL="https://github.com/${{ github.repository }}"
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "none")
          # Normalize and get unique contributors by email to avoid duplicates
          contributors=$(git log --format='%an <%ae>' | sort -u | while read -r line; do
            full_name=$(echo "$line" | sed 's/ <.*>//')
            email=$(echo "$line" | sed 's/.*<\(.*\)>/\1/' | tr '[:upper:]' '[:lower:]') # Normalize email case
            username=$(echo "$email" | cut -d'@' -f1)
            if echo "$full_name" | grep -q " "; then
              echo "* $full_name ([@$username](https://github.com/$username))"
            else
              echo "* [@$full_name](https://github.com/$full_name)"
            fi
          done | sort -u) # Extra sort -u to ensure no duplicates
          commits=$(git log --format='* [%h]('$REPO_URL'/commit/%H) %s ([%an](https://github.com/%an))')
          contributors=$'\n'"${contributors}"$'\n'
          contributors="${contributors//'%'/'%25'}"
          contributors="${contributors//$'\n'/'%0A'}"
          contributors="${contributors//$'\r'/'%0D'}"
          echo "list=$contributors" >> $GITHUB_OUTPUT
          commits=$'\n'"${commits}"$'\n'
          commits="${commits//'%'/'%25'}"
          commits="${commits//$'\n'/'%0A'}"
          commits="${commits//$'\r'/'%0D'}"
          echo "commits=$commits" >> $GITHUB_OUTPUT

      - name: Display Release Content
        run: |
          echo "### Changes"
          printf '%s\n' "${{ steps.changelog.outputs.content }}" | sed 's/%0A/\n/g'
          echo "_For more details, see the full [changelog](${{ github.server_url }}/${{ github.repository }}/blob/master/CHANGELOG.md) in the repository_"
          echo ""
          echo "### Contributors"
          printf '%s\n' "${{ steps.contributors.outputs.list }}" | sed 's/%0A/\n/g'
          echo ""
          echo "### Commits"
          printf '%s\n' "${{ steps.contributors.outputs.commits }}" | sed 's/%0A/\n/g'
