name: Test Release Creation

on:
  push:
    branches:
      - release-test

permissions:
  contents: write  # Included for consistency, though not strictly needed for logging

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history

      - name: Fetch all branches and set branch
        run: |
          git fetch origin +refs/heads/*:refs/remotes/origin/*
          #git checkout release-test

      - name: Get Changelog Entry
        id: changelog
        run: |
          changelog=$(sed -n '/^## Version /{n; :a;p;n;/^$/q;ba}' CHANGELOG.md | sed '/^$/d')
          changelog=$'\n'"${changelog}"$'\n'
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "content=$changelog" >> $GITHUB_OUTPUT

      - name: Get Contributors and Commits
        id: contributors
        run: |
          REPO_URL="https://github.com/${{ github.repository }}"
          # Get contributors sorted by commit count and deduplicated using git log
          contributors=$(git log --format='%an <%ae>' | sort | uniq -c | sort -nr | awk '{ $1=""; sub(/^[ \t]+/, ""); name=substr($0, 1, index($0, "<")-1); email=substr($0, index($0, "<")+1, index($0, ">")-index($0, "<")-1); username=tolower(substr(email, 1, index(email, "@")-1)); print "* " (name ~ / / ? name " ([@" username "](https://github.com/" username "))" : "[@" name "](https://github.com/" name ")") }' | sort -u)
          # Get all commits and escape % in messages
          git log --format='* [%h]('$REPO_URL'/commit/%H) %s ([%an](https://github.com/%an))' | sed 's/%/%25/g' > commits.txt
          commits=$(cat commits.txt)
          # Use GitHub Actions multi-line output syntax with a delimiter
          delimiter=$(openssl rand -hex 8)
          {
            echo "list<<$delimiter"
            echo "$contributors"
            echo "$delimiter"
          } >> $GITHUB_OUTPUT
          {
            echo "commits<<$delimiter"
            echo "$commits"
            echo "$delimiter"
          } >> $GITHUB_OUTPUT

      - name: Display Release Content
        run: |
          echo "### Changes"
          echo "${{ steps.changelog.outputs.content }}" | sed 's/%0A/\n/g'
          echo "_For more details, see the full [changelog](${{ github.server_url }}/${{ github.repository }}/blob/master/CHANGELOG.md) in the repository_"
          echo ""
          echo "### Contributors"
          echo "${{ steps.contributors.outputs.list }}"
          echo ""
          echo "### Commits"
          cat commits.txt
